#! /bin/sh

picom &
xwallpaper --zoom "$HOME/Pictures/wall.png" &
xsetroot -cursor_name left_ptr &
xset r rate 350 20 &
eww open bar &
dunst -conf $HOME/.config/dunst/dunstrc &
ibus-daemon -drxR &
mpd &
xrdb merge "$HOME/.Xresources" &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        0
bspc config window_gap          17

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Chromium desktop='^2'
